### ISSUE TITLE
second test on BleskOS

### ISSUE THREAD

**Issue by davidgaosheng** [VendelinSlezak/BleskOS#18]
Another real machine. 
I can not choose "BleskOS" or "BleskOS special boot options" from the boot menu, because the usb keyboard failed to response. Before the test, legacy usb mode had been turned off. From the BIOS list I see that there are only EHCI controllers without UHCI companions in the computer.

**Comment by VendelinSlezak** [comment]
Thank you for testing BleskOS on real computer!
At first I would try to enable legacy USB mode, and if it won't help, search if companion controllers are not disabled in BIOS somehow. Every EHCI controller should have companion controllers, because EHCI controller do not support low-speed devices(USB mouse/USB keyboard). So without them, you should not be able to use USB keyboard even in BIOS. Boot menu relies on BIOS keyboard interrupt. So if you can use USB keyboard in BIOS, it is probably some wrong setting in BIOS.

**Comment by davidgaosheng** [comment]
in the second computer, there are two speed-rating EHCIs, this is no UHCI in it. the speed-rating is a problem.

**Comment by VendelinSlezak** [comment]
Do you have xHCI controller on this computer? If yes, it would explain this. xHCI handles USB devices of all speed. Unfortunately BleskOS now do not have driver for xHCI, so it can not see your keyboard. And it is common that even that xHCI handles all outside USB ports, some devices inside computer are connected to special EHCI port that of course do not need companion controllers because it is hardwired for concrete device.

**Comment by davidgaosheng** [comment]
![image](https://github.com/VendelinSlezak/BleskOS/assets/78395860/4c01d48f-f035-4118-a45e-b1537a500c0a)
that's what Ubuntu [lsusb] said about the HC. the server is not with a xHC(USB 3.0), it's with a EHCI. The manual of the computer says it has USB 2.0 ports.

**Comment by davidgaosheng** [comment]
I suggest that you have to drive hubs to recongnize keyboards and mouses attached.

**Comment by VendelinSlezak** [comment]
Well, yes, only way how to connect low-speed device into EHCI is through USB hub, because hub itself is not low-speed device. Do you use USB hubs? If not, it seems strange to me for computer have USB hubs inside, but who knows. Please can you try this image? After boot it will not show Main window, but System log with USB part, so we will be able to see what BleskOS detects. If there are hubs inside, we should see them being enumerated
[bleskos_2023_update_4_only_USB_logs.img.zip](https://github.com/VendelinSlezak/BleskOS/files/12795290/bleskos_2023_update_4_only_USB_logs.img.zip)
.

**Comment by VendelinSlezak** [comment]
I look again and it really seems that device "Intel Corp. Integrated Rate Matching Hub" is actual hub connected to EHCI controller. So I will try to write driver for USB hubs. I hope I will finish it in reasonable amount of time, maybe few weeks.

**Comment by davidgaosheng** [comment]
Very well. I am looking forward a new version of BleskOS, which will be driving Ehci with rate matching hubs. Then we will see if BleskOS  runs on rate matching husbs. BTW, https://github.com/pdoane/osdev/blob/master/usb/hub.c might be a reference.

**Comment by VendelinSlezak** [comment]
Update 8 have driver for USB hubs connected to UHCI and OHCI so I hope that I will release version that will support hubs on EHCI next week.

**Comment by VendelinSlezak** [comment]
Update 9 support USB hubs also on EHCI controller, however it do not support USB mouse/keyboard on EHCI controller, I need to figure out how to write driver for it properly. However it would be nice if you would already try this update to confirm if you can see hubs listed in Connected hardware.

**Comment by davidgaosheng** [comment]
Yes, I have tried update 9 in my server computer. it found the three usb hubs, keyboard and mouse being unable to function.

**Comment by davidgaosheng** [comment]
in the begining BleskOS listed 3 usb hubs, and after a while it listed 2 of them.

**Comment by VendelinSlezak** [comment]
That's interesting. Can you please try this image? After boot it directly go to USB system log.
[bleskos_2023_update_9_directly_usb_system_log.zip](https://github.com/VendelinSlezak/BleskOS/files/13121793/bleskos_2023_update_9_directly_usb_system_log.zip)

**Comment by davidgaosheng** [comment]
![log](https://github.com/VendelinSlezak/BleskOS/assets/78395860/b48d5e3a-72b0-46ec-8650-7027eaa04152)

**Comment by VendelinSlezak** [comment]
So finally I have version where USB low/full speed devices works under EHCI controller. I tested it on my USB hub and also on computer that have USB hubs built inside. Please can you test this version if it also works on your computer? Image below goes directly into system log.
[bleskos_2023_test_update_10_with_ehci_hub_working_img.zip](https://github.com/VendelinSlezak/BleskOS/files/13195558/bleskos_2023_test_update_10_with_ehci_hub_working_img.zip)

**Comment by davidgaosheng** [comment]
good news. I could move mouse cursor on the screen. Also I could scroll down / up log text with middle mouse button and arrow keys on keyboard. There are still some warning messages.
![p1](https://github.com/VendelinSlezak/BleskOS/assets/78395860/1df3d9a4-290e-4e27-974b-10c3c776cfa0)
![p2](https://github.com/VendelinSlezak/BleskOS/assets/78395860/a88d8d23-8e0c-41be-a805-56caa8fd8824)

**Comment by davidgaosheng** [comment]
To make screen clearer, I scrolled to blank the screen. I plugged out keyboard and plugged it in again, BleskOS displayed nothing about the removing and insertion of the keyboard untill I moved the mouse. Similar to the mouse.
![p](https://github.com/VendelinSlezak/BleskOS/assets/78395860/e8366de7-4302-4c71-a267-8fe1269dceee)

**Comment by VendelinSlezak** [comment]
Thats great. Error message after detecting USB mouse is fine, it is common that some UBS mouse refuse to execute some command like Set Idle, because it is optional. More interesting are other error messages. Can you try update 10 to see how it works?

**Comment by davidgaosheng** [comment]
yeah I tested update 10, and it behaved very well except for disallowing two keyboards to fuction in the same time.

**Comment by VendelinSlezak** [comment]
Nice to hear that. Yes, BleskOS now do not support multiple USB keyboards/mouses connected at same time. I am planning at some point on future to allow to connect 2 USB keyboards/mouses, but I also think for now it is good enough, so I am closing this issue.
