### ISSUE TITLE
Better code style.

### ISSUE THREAD

**Issue by hahahahacker2009** [VendelinSlezak/BleskOS#23]
Small feedback for maintainability:
Little reading shows that the project's code style is so terrible!
The fundamentals are not even followed:
- You don't even break functions' { on own line, which is not a good style
- 80 character per line limit (perhaps your software is SO modern?)
- use tab character to indent and tab character should be 8 character
- a space after if, for,...
- Maybe many more
Recommended reading:
https://man.openbsd.org/style.9
https://www.kernel.org/doc/Documentation/process/coding-style.rst

**Comment by VendelinSlezak** [comment]
Thank you for feedback. I like my style of coding and for me it is much mode readable than code with rules above.
“You don't even break functions' { on own line, which is not a good style” I hate code that is written in this style and I consider it much more messy than when you just leave { in same line.
“80 character per line limit (perhaps your software is SO modern?)” I would love that, but often it is not possible.
“use tab character to indent and tab character should be 8 character” I do not like tabs because it goes messy with spaces. Also 8 characters per tab is too much and would make code for me harder to read because of its big layout.
“a space after if, for,...” I consider this as disadvantage because it separates two parts of same command without reason. Code is better readable when everything what constitutes one command is joined.
And so on.
